### ISSUE TITLE
FINANCIERO002 - ReAjuste en el modelo de negocio

### ISSUE THREAD

**Issue by balthierStar** [QuestCali/QuestComercial#133]
Luego de Validar los datos de los reportes, se evidenció que la regla de los siguientes reportes no corresponde: 
- [x] **FINANCIERO002_1:** Saldo Corriente vencido por edades ->Especificar adecuadamente la regla. #134 

- [x] **FINANCIERO002_2:** Análisis de Recaudo ->Tiene unos campos con una especificación inadecuada. #135
> - [x] **TOTAL** -> por Presupuesto.
> - [x] **Cumplimiento** -> por % Cumplimiento.

- [x] **FINANCIERO002_3:** Saldo Vencido por Edades -> La definición de este reporte no fue adecuada #136

**Comment by balthierStar** [comment]
Se pasa a el area para ser revisado.
